import type { Metadata } from "next";
import { Georama } from "next/font/google";
import "./globals.css";
import HeroSection from "@/components/hero-section";
import Footer from "@/components/footer";

const georama = Georama({
	variable: "--font-georama",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${georama.variable} antialiased`}>
				<HeroSection />
				{children}
				<Footer />
			</body>
		</html>
	);
}
